cc_library(
    name = "format",
    srcs = ["format.h"],
)

cc_test(
    name = "format_test",
    srcs = ["format_test.cc"],
    deps = [
        ":format",
        "@catch2//:catch2_main",
    ],
)
